"""
Unified reproducible evaluation pipeline (revision build).

Everything the manuscript reports is produced HERE, from raw predictions, in one
run. No hardcoded metrics, no mock distributions. Figures are generated by
generate_figures.py strictly from the artifacts this script writes.

Reviewer fixes implemented by construction:
  - Leakage-free preprocessing: encoding/scaling fit inside each CV fold
    (sklearn Pipeline/ColumnTransformer).                              [R3-6]
  - Age treated as a protected attribute -> excluded from predictors, so it
    cannot appear as a model feature in SHAP/permutation.              [R3-4]
  - CatBoost uses native categorical handling (cat_features); LogReg/RF use
    one-hot. Rationale now matches implementation.                     [R3-8]
  - Explicit, logged hyperparameters for every model.                  [R3-7]
  - Class weighting run as a sensitivity (weighted vs unweighted) with its
    effect on calibration measured.                                    [R3-11]
  - Clean leave-group-out compensation ablation, both directions, same splits,
    same settings.                                                     [R3-5]
  - Real bootstrap CI (method logged), 7-seed sweep, SHAP + permutation with
    faithfulness/stability/sanity checks, Cramer's V, disparate-impact ratios,
    DBSCAN/KMeans/PCA-KMeans/GMM, MI with estimator + permutation null,
    ECE with bootstrap CI and adaptive binning, threshold sensitivity,
    train/test overfitting gap.               [R1-2, R1-3, R1-5, R1-6, R3-2/3/9/10/12]

Primary result = stratified 5-fold CV (seed 42). A single stratified holdout is
reported as a robustness illustration (confusion matrix, bootstrap, SHAP).
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import (
    roc_auc_score, brier_score_loss, average_precision_score,
    accuracy_score, confusion_matrix, silhouette_score,
)
from sklearn.inspection import permutation_importance
from sklearn.feature_selection import mutual_info_classif
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN
from sklearn.mixture import GaussianMixture
from catboost import CatBoostClassifier, Pool
try:
    import shap                       # optional; CatBoost native TreeSHAP used if absent
except Exception:
    shap = None

warnings.filterwarnings("ignore")
RNG = 42
np.random.seed(RNG)

BASE = Path(__file__).parent
DATA = BASE / "data" / "ibm_hr_attrition.csv"
RESDIR = BASE / "results"
RESDIR.mkdir(exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# Data
# ─────────────────────────────────────────────────────────────────────────────
def load_data():
    df = pd.read_csv(DATA, encoding="utf-8-sig")          # strips BOM on 'Age'
    df.columns = [c.strip() for c in df.columns]
    y = (df["Attrition"].astype(str).str.strip() == "Yes").astype(int).values

    # constant / identifier columns
    drop_const = [c for c in ["EmployeeCount", "EmployeeNumber", "Over18",
                              "StandardHours"] if c in df.columns]
    protected = ["Gender", "Age", "MaritalStatus"]

    # ── structural indices (row-wise, parameter-free -> no leakage) ──────────
    df["OvertimeFrequency"]       = (df["OverTime"] == "Yes").astype(int)
    df["SatisfactionJobLevel"]    = df["JobSatisfaction"] * df["JobLevel"]
    df["TenurePromotionRatio"]    = df["YearsAtCompany"] / (df["YearsSinceLastPromotion"] + 1)
    df["OvertimeBalanceRatio"]    = df["OvertimeFrequency"] / (df["WorkLifeBalance"] + 1)
    df["CompensationProgression"] = df["MonthlyIncome"] / (df["YearsAtCompany"] + 1)
    df["PerfCompAlignment"]       = df["PerformanceRating"] * df["MonthlyIncome"]
    df["WorkArrangement"]         = df["BusinessTravel"].map(
        {"Non-Travel": 0, "Travel_Rarely": 1, "Travel_Frequently": 2}).fillna(0)
    df["MultiSatisfaction"]       = (df["JobSatisfaction"] +
                                     df["EnvironmentSatisfaction"] +
                                     df["RelationshipSatisfaction"]) / 3

    # protected attribute encodings (for fairness only)
    prot = pd.DataFrame({
        "gender":  (df["Gender"] == "Male").astype(int).values,
        "marital": df["MaritalStatus"].astype("category").cat.codes.values,
        "ageband": pd.cut(df["Age"], bins=[17, 29, 39, 49, 120],
                          labels=[0, 1, 2, 3]).astype(int).values,
        "compband": pd.qcut(df["MonthlyIncome"], 4, labels=[0, 1, 2, 3]).astype(int).values,
        "dept":    df["Department"].astype("category").cat.codes.values,
    })

    X = df.drop(columns=["Attrition"] + drop_const + protected)
    cat_cols = X.select_dtypes(include=["object", "category", "string"]).columns.tolist()
    # ensure categorical columns are plain python strings for CatBoost
    for c in cat_cols:
        X[c] = X[c].astype(str)
    num_cols = [c for c in X.columns if c not in cat_cols]

    # compensation feature group for the ablation (explicit, logged)
    comp_group = ["MonthlyIncome", "MonthlyRate", "DailyRate", "HourlyRate",
                  "PercentSalaryHike", "StockOptionLevel",
                  "CompensationProgression", "PerfCompAlignment"]
    comp_group = [c for c in comp_group if c in X.columns]
    return df, X, y, cat_cols, num_cols, comp_group, prot


# ─────────────────────────────────────────────────────────────────────────────
# Model builders (leakage-free; fit inside each fold)
# ─────────────────────────────────────────────────────────────────────────────
CATBOOST_PARAMS = dict(iterations=400, learning_rate=0.05, depth=6,
                       random_seed=RNG, verbose=0, allow_writing_files=False)
RF_PARAMS = dict(n_estimators=400, max_depth=None, min_samples_leaf=2,
                 random_state=RNG, n_jobs=-1)
LOGREG_PARAMS = dict(max_iter=2000, C=1.0, random_state=RNG)


def make_sklearn_pipe(kind, cat_cols, num_cols):
    if kind == "logreg":
        pre = ColumnTransformer([
            ("num", StandardScaler(), num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)])
        clf = LogisticRegression(**LOGREG_PARAMS)
    elif kind == "rf":
        pre = ColumnTransformer([
            ("num", "passthrough", num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)])
        clf = RandomForestClassifier(**RF_PARAMS)
    elif kind == "dummy":
        pre = ColumnTransformer([
            ("num", "passthrough", num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)])
        clf = DummyClassifier(strategy="prior")
    else:
        raise ValueError(kind)
    return Pipeline([("pre", pre), ("clf", clf)])


def fit_catboost(Xtr, ytr, cat_cols, class_weights=None):
    params = dict(CATBOOST_PARAMS)
    if class_weights is not None:
        params["class_weights"] = class_weights
    m = CatBoostClassifier(**params)
    m.fit(Pool(Xtr, ytr, cat_features=cat_cols))
    return m


# ─────────────────────────────────────────────────────────────────────────────
# Metrics
# ─────────────────────────────────────────────────────────────────────────────
def ece_uniform(y, p, n_bins=10):
    bins = np.linspace(0, 1, n_bins + 1)
    val = 0.0
    for lo, hi in zip(bins[:-1], bins[1:]):
        m = (p >= lo) & (p < hi if hi < 1 else p <= hi)
        if m.sum():
            val += m.sum() * abs(y[m].mean() - p[m].mean())
    return float(val / len(y))


def ece_adaptive(y, p, n_bins=10):
    """Equal-count (adaptive) binning ECE — stable under few positives. [R1-3]"""
    order = np.argsort(p)
    y, p = y[order], p[order]
    val = 0.0
    for idx in np.array_split(np.arange(len(y)), n_bins):
        if len(idx):
            val += len(idx) * abs(y[idx].mean() - p[idx].mean())
    return float(val / len(y))


def reliability_bins(y, p, n_bins=10):
    bins = np.linspace(0, 1, n_bins + 1)
    centers, frac, conf, cnt = [], [], [], []
    for lo, hi in zip(bins[:-1], bins[1:]):
        m = (p >= lo) & (p < hi if hi < 1 else p <= hi)
        if m.sum():
            centers.append((lo + hi) / 2); frac.append(float(y[m].mean()))
            conf.append(float(p[m].mean())); cnt.append(int(m.sum()))
    return dict(centers=centers, frac_pos=frac, conf=conf, count=cnt)


def dpd(y_pred, a):
    r = [y_pred[a == g].mean() for g in np.unique(a)]
    return float(max(r) - min(r))


def eod(y_true, y_pred, a):
    tpr, fpr = [], []
    for g in np.unique(a):
        m = a == g
        cm = confusion_matrix(y_true[m], y_pred[m], labels=[0, 1])
        d1 = cm[1, 0] + cm[1, 1]; d0 = cm[0, 0] + cm[0, 1]
        tpr.append(cm[1, 1] / d1 if d1 else 0.0)
        fpr.append(cm[0, 1] / d0 if d0 else 0.0)
    return float(max(max(tpr) - min(tpr), max(fpr) - min(fpr)))


def disparate_impact(y_pred, a):
    r = np.array([y_pred[a == g].mean() for g in np.unique(a)])
    r = r[r > 0]
    return float(r.min() / r.max()) if len(r) else float("nan")


def cramers_v(y_pred, a):
    ct = pd.crosstab(y_pred, a)
    chi2 = stats.chi2_contingency(ct)[0]
    n = ct.values.sum()
    r, k = ct.shape
    denom = n * (min(r, k) - 1)
    return float(np.sqrt(chi2 / denom)) if denom > 0 else 0.0


# ─────────────────────────────────────────────────────────────────────────────
# 1) Stratified 5-fold CV — primary result, all models, full + ablation
# ─────────────────────────────────────────────────────────────────────────────
def run_cv(X, y, cat_cols, num_cols, comp_group, prot):
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RNG)

    def cv_scores_generic(build, feat_cols, cats, nums, use_catboost=False,
                          class_weights=None, collect=False):
        aucs, briers, aps, accs, train_aucs = [], [], [], [], []
        pool = {"yt": [], "yp": [], "pr": [], "idx": []}
        for tr, te in skf.split(X, y):
            Xtr, Xte = X.iloc[tr][feat_cols], X.iloc[te][feat_cols]
            ytr, yte = y[tr], y[te]
            if use_catboost:
                m = fit_catboost(Xtr, ytr, cats, class_weights)
                p = m.predict_proba(Xte)[:, 1]
                ptr = m.predict_proba(Xtr)[:, 1]
            else:
                pipe = build()
                pipe.fit(Xtr, ytr)
                p = pipe.predict_proba(Xte)[:, 1]
                ptr = pipe.predict_proba(Xtr)[:, 1]
            pred = (p >= 0.5).astype(int)
            aucs.append(roc_auc_score(yte, p)); briers.append(brier_score_loss(yte, p))
            aps.append(average_precision_score(yte, p)); accs.append(accuracy_score(yte, pred))
            train_aucs.append(roc_auc_score(ytr, ptr))
            if collect:
                pool["yt"].extend(yte); pool["yp"].extend(pred)
                pool["pr"].extend(p); pool["idx"].extend(te)
        out = dict(auc=aucs, brier=briers, ap=aps, acc=accs, train_auc=train_aucs)
        return (out, pool) if collect else out

    all_feats = list(X.columns)
    non_comp = [c for c in all_feats if c not in comp_group]
    cats_full = [c for c in cat_cols if c in all_feats]
    cats_noncomp = [c for c in cat_cols if c in non_comp]
    cats_comp = [c for c in cat_cols if c in comp_group]

    results = {}

    # CatBoost full — unweighted (primary) and weighted (sensitivity)
    cb_full_uw, pool_uw = cv_scores_generic(
        None, all_feats, cats_full, num_cols, use_catboost=True,
        class_weights=None, collect=True)
    cb_full_w, pool_w = cv_scores_generic(
        None, all_feats, cats_full, num_cols, use_catboost=True,
        class_weights={0: 1, 1: 5}, collect=True)

    # Other model families (full features)
    lr_full = cv_scores_generic(
        lambda: make_sklearn_pipe("logreg", cats_full, [c for c in num_cols if c in all_feats]),
        all_feats, cats_full, num_cols)
    rf_full = cv_scores_generic(
        lambda: make_sklearn_pipe("rf", cats_full, [c for c in num_cols if c in all_feats]),
        all_feats, cats_full, num_cols)
    dummy_full = cv_scores_generic(
        lambda: make_sklearn_pipe("dummy", cats_full, [c for c in num_cols if c in all_feats]),
        all_feats, cats_full, num_cols)

    # Ablation (CatBoost, same splits/settings as primary weighted model):
    # compensation-removed & compensation-only
    CW = {0: 1, 1: 5}
    cb_nocomp = cv_scores_generic(None, non_comp, cats_noncomp,
                                  [c for c in num_cols if c in non_comp],
                                  use_catboost=True, class_weights=CW)
    cb_componly = cv_scores_generic(None, comp_group, cats_comp,
                                    [c for c in num_cols if c in comp_group],
                                    use_catboost=True, class_weights=CW)

    def summ(d):
        out = {}
        for k, v in d.items():
            v = np.array(v, float)
            m, s, n = v.mean(), v.std(ddof=1), len(v)
            out[k] = dict(mean=round(float(m), 4), std=round(float(s), 4),
                          ci_lo=round(float(m - 1.96 * s / np.sqrt(n)), 4),
                          ci_hi=round(float(m + 1.96 * s / np.sqrt(n)), 4))
        return out

    results["models"] = {
        "catboost_full_unweighted": summ(cb_full_uw),
        "catboost_full_weighted_5x": summ(cb_full_w),
        "logreg_full": summ(lr_full),
        "randomforest_full": summ(rf_full),
        "dummy_full": summ(dummy_full),
        "catboost_compensation_removed": summ(cb_nocomp),
        "catboost_compensation_only": summ(cb_componly),
    }
    # ablation deltas (both directions, explicit; primary = weighted model)
    full_auc = results["models"]["catboost_full_weighted_5x"]["auc"]["mean"]
    results["ablation"] = {
        "full_auc": full_auc,
        "compensation_removed_auc": results["models"]["catboost_compensation_removed"]["auc"]["mean"],
        "compensation_only_auc": results["models"]["catboost_compensation_only"]["auc"]["mean"],
        "delta_removing_compensation": round(full_auc - results["models"]["catboost_compensation_removed"]["auc"]["mean"], 4),
        "delta_full_minus_comp_only": round(full_auc - results["models"]["catboost_compensation_only"]["auc"]["mean"], 4),
        "comp_group": comp_group,
    }

    # overfitting gap (CatBoost full, primary weighted model)
    results["overfitting"] = {
        "train_auc_mean": summ(cb_full_w)["train_auc"]["mean"],
        "test_auc_mean": summ(cb_full_w)["auc"]["mean"],
        "gap": round(summ(cb_full_w)["train_auc"]["mean"] - summ(cb_full_w)["auc"]["mean"], 4),
    }

    return results, pool_uw, pool_w, all_feats, cats_full


# ─────────────────────────────────────────────────────────────────────────────
# main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    df, X, y, cat_cols, num_cols, comp_group, prot = load_data()
    print(f"Loaded: X={X.shape}, base_rate={y.mean():.4f}, "
          f"cat_cols={len(cat_cols)}, comp_group={len(comp_group)}")

    out = {"dataset": {"n": int(len(y)), "n_features": int(X.shape[1]),
                       "base_rate": round(float(y.mean()), 4),
                       "is_synthetic": True,
                       "cat_features": cat_cols, "comp_group": comp_group}}

    print("\n[1/7] Stratified 5-fold CV (all models, ablation, overfitting) …")
    cv, pool_uw, pool_w, all_feats, cats_full = run_cv(
        X, y, cat_cols, num_cols, comp_group, prot)
    out.update(cv)

    # pooled CV predictions. Primary = weighted 5:1 (consistent with prior submission);
    # unweighted retained as the R3-11 calibration sensitivity.
    yt = np.array(pool_w["yt"]); pr = np.array(pool_w["pr"])
    yp = np.array(pool_w["yp"]); idx = np.array(pool_w["idx"])
    yt_u = np.array(pool_uw["yt"]); pr_u = np.array(pool_uw["pr"])

    print("[2/7] Calibration (ECE uniform + adaptive, bootstrap CI, weighted vs not) …")
    def boot_ece(y_, p_, fn, B=1000):
        vals = []
        n = len(y_)
        rs = np.random.RandomState(RNG)
        for _ in range(B):
            s = rs.randint(0, n, n)
            vals.append(fn(y_[s], p_[s]))
        return round(float(np.percentile(vals, 2.5)), 4), round(float(np.percentile(vals, 97.5)), 4)
    out["calibration"] = {
        "primary_model": "catboost_full_weighted_5x",
        "weighted_5x": {
            "ece_uniform_10": round(ece_uniform(yt, pr), 4),
            "ece_uniform_10_ci95": boot_ece(yt, pr, ece_uniform),
            "ece_adaptive_10": round(ece_adaptive(yt, pr), 4),
            "ece_adaptive_10_ci95": boot_ece(yt, pr, ece_adaptive),
            "brier": round(brier_score_loss(yt, pr), 4),
            "mean_pred": round(float(pr.mean()), 4),
            "reliability": reliability_bins(yt, pr),
        },
        "unweighted": {
            "ece_uniform_10": round(ece_uniform(yt_u, pr_u), 4),
            "ece_uniform_10_ci95": boot_ece(yt_u, pr_u, ece_uniform),
            "ece_adaptive_10": round(ece_adaptive(yt_u, pr_u), 4),
            "brier": round(brier_score_loss(yt_u, pr_u), 4),
            "mean_pred": round(float(pr_u.mean()), 4),
        },
        "note": "base_rate=%.4f; compare mean_pred to base_rate to see weighting inflation" % y.mean(),
    }

    print("[3/7] Holdout split: confusion matrix + bootstrap AUC CI + SHAP + permutation …")
    Xtr, Xte, ytr, yte, itr, ite = train_test_split(
        X, y, np.arange(len(y)), test_size=0.2, stratify=y, random_state=RNG)
    m = fit_catboost(Xtr[all_feats], ytr, cats_full, class_weights={0: 1, 1: 5})
    p_hold = m.predict_proba(Xte[all_feats])[:, 1]
    pred_hold = (p_hold >= 0.5).astype(int)
    cm = confusion_matrix(yte, pred_hold, labels=[0, 1])
    # other models on the same holdout (for a real multi-model ROC figure)
    holdout_probs = {"catboost": p_hold}
    for kind, key in [("logreg", "logreg"), ("rf", "randomforest"), ("dummy", "dummy")]:
        pipe = make_sklearn_pipe(kind, cats_full, [c for c in num_cols if c in all_feats])
        pipe.fit(Xtr, ytr)
        holdout_probs[key] = pipe.predict_proba(Xte)[:, 1]
    out["holdout_auc_by_model"] = {k: round(roc_auc_score(yte, v), 4)
                                   for k, v in holdout_probs.items()}
    out["holdout"] = {
        "test_size": int(len(yte)), "n_positive": int(yte.sum()),
        "auc": round(roc_auc_score(yte, p_hold), 4),
        "brier": round(brier_score_loss(yte, p_hold), 4),
        "confusion_matrix": {"tn": int(cm[0, 0]), "fp": int(cm[0, 1]),
                             "fn": int(cm[1, 0]), "tp": int(cm[1, 1])},
    }
    # bootstrap AUC CI (percentile, paired resample of test predictions)
    rs = np.random.RandomState(RNG)
    baucs = []
    for _ in range(1000):
        s = rs.randint(0, len(yte), len(yte))
        if len(np.unique(yte[s])) < 2:
            continue
        baucs.append(roc_auc_score(yte[s], p_hold[s]))
    out["bootstrap"] = {
        "method": "percentile, 1000 paired resamples of holdout test predictions",
        "auc_point": round(roc_auc_score(yte, p_hold), 4),
        "auc_mean": round(float(np.mean(baucs)), 4),
        "ci95": [round(float(np.percentile(baucs, 2.5)), 4),
                 round(float(np.percentile(baucs, 97.5)), 4)],
    }

    # SHAP on holdout test. Prefer shap.TreeExplainer; else CatBoost native TreeSHAP
    # (get_feature_importance(type="ShapValues") returns exact tree Shapley values).
    shap_src = "shap.TreeExplainer"
    try:
        if shap is None:
            raise RuntimeError("shap package not installed")
        sv = shap.TreeExplainer(m).shap_values(
            Pool(Xte[all_feats], yte, cat_features=cats_full))
        sv = np.asarray(sv[1] if isinstance(sv, list) else sv)
    except Exception as e:
        shap_src = "catboost native ShapValues (exact TreeSHAP)"
        print(f"  shap.TreeExplainer unavailable ({e}); using {shap_src}")
        sv = np.asarray(m.get_feature_importance(
            Pool(Xte[all_feats], yte, cat_features=cats_full), type="ShapValues"))
    if sv.shape[1] == len(all_feats) + 1:              # trailing base-value column
        sv = sv[:, :len(all_feats)]
    mean_abs = np.abs(sv).mean(axis=0)
    shap_imp = sorted(zip(all_feats, mean_abs), key=lambda t: -t[1])
    out["shap"] = {"source": shap_src,
                   "note": "holdout test; Age excluded from features",
                   "top": [{"feature": f, "mean_abs_shap": round(float(v), 5)}
                           for f, v in shap_imp[:15]]}

    # permutation importance (holdout test, roc_auc)
    perm_imp = []
    try:
        perm = permutation_importance(m, Xte[all_feats], yte, n_repeats=30,
                                      random_state=RNG, scoring="roc_auc")
        perm_imp = sorted(zip(all_feats, perm.importances_mean, perm.importances_std),
                          key=lambda t: -t[1])
        out["permutation"] = {"scoring": "roc_auc, n_repeats=30, holdout test",
                              "top": [{"feature": f, "mean": round(float(mn), 5),
                                       "std": round(float(sd), 5)}
                                      for f, mn, sd in perm_imp[:15]]}
    except Exception as e:
        print(f"  permutation_importance failed: {e}")
        out["permutation"] = {"error": str(e)}

    print("[4/7] XAI faithfulness / stability / sanity checks …")
    out["xai_validation"] = {}
    try:
        # rank agreement SHAP vs permutation
        if perm_imp:
            perm_map = {f: mn for f, mn, _ in perm_imp}
            shap_map = {f: v for f, v in shap_imp}
            feats_common = list(shap_map)
            rho = stats.spearmanr([shap_map[f] for f in feats_common],
                                  [perm_map[f] for f in feats_common]).correlation
            out["xai_validation"]["shap_vs_permutation_spearman"] = round(float(rho), 3)

        # deletion faithfulness: mask top-k (by SHAP) vs random, measure AUC drop
        def masked_auc(order):
            drops = []
            for k in range(0, min(10, len(order)) + 1):
                Xmk = Xte[all_feats].copy()
                for f in order[:k]:
                    Xmk[f] = Xtr[f].median() if f in num_cols else Xtr[f].mode().iloc[0]
                drops.append(roc_auc_score(yte, m.predict_proba(Xmk)[:, 1]))
            return drops
        del_top = masked_auc([f for f, _ in shap_imp])
        del_rnd = masked_auc(list(np.random.RandomState(RNG).permutation(all_feats)))
        out["xai_validation"]["deletion_auc_top"] = [round(float(v), 4) for v in del_top]
        out["xai_validation"]["deletion_auc_random"] = [round(float(v), 4) for v in del_rnd]
        out["xai_validation"]["deletion_faithfulness_gap"] = round(
            float(np.mean(np.array(del_rnd) - np.array(del_top))), 4)

        # sanity: random-label model importances should collapse
        yshuf = np.random.RandomState(RNG).permutation(ytr)
        m_rand = fit_catboost(Xtr[all_feats], yshuf, cats_full)
        perm_rand = permutation_importance(m_rand, Xte[all_feats], yte, n_repeats=10,
                                           random_state=RNG, scoring="roc_auc")
        out["xai_validation"]["sanity_random_label_max_perm_importance"] = round(
            float(perm_rand.importances_mean.max()), 5)
    except Exception as e:
        print(f"  xai_validation partial failure: {e}")
        out["xai_validation"]["error"] = str(e)

    print("[5/7] Fairness: DPD, EOD, disparate impact, Cramer's V (pooled CV preds) …")
    prot_te = prot.iloc[idx].reset_index(drop=True)
    fair = {}
    for name in ["gender", "marital", "ageband", "compband", "dept"]:
        a = prot_te[name].values
        fair[name] = {
            "dpd": round(dpd(yp, a), 4),
            "eod": round(eod(yt, yp, a), 4),
            "disparate_impact": round(disparate_impact(yp, a), 4),
            "cramers_v": round(cramers_v(yp, a), 4),
        }
    out["fairness"] = fair
    # threshold sensitivity for escalation flags
    out["threshold_sensitivity"] = {
        "eod_thresholds": {str(t): [n for n in fair if fair[n]["eod"] > t]
                           for t in [0.10, 0.15, 0.20, 0.25]},
        "cramers_v_thresholds": {str(t): [n for n in fair if fair[n]["cramers_v"] > t]
                                 for t in [0.10, 0.15, 0.20, 0.25]},
        "di_thresholds": {str(t): [n for n in fair if fair[n]["disparate_impact"] < t]
                          for t in [0.80, 0.90]},
    }

    print("[6/7] Proxy MI audit with estimator + permutation null …")
    # encode features numerically for MI (one-hot cats), fixed estimator
    Xmi = pd.get_dummies(X, columns=cat_cols)
    Xmi = Xmi.select_dtypes(include=[np.number]).fillna(0)
    mi_feats = Xmi.columns.tolist()
    proxy = {}
    for name in ["gender", "marital", "ageband"]:
        a = prot[name].values
        mi = mutual_info_classif(Xmi.values, a, discrete_features=False,
                                 random_state=RNG, n_neighbors=3)
        top = np.argsort(mi)[::-1][:5]
        # permutation null for the single top feature
        top1 = int(top[0])
        null = []
        rs = np.random.RandomState(RNG)
        for _ in range(200):
            ash = rs.permutation(a)
            null.append(mutual_info_classif(Xmi.values[:, [top1]], ash,
                        discrete_features=False, random_state=None, n_neighbors=3)[0])
        null = np.array(null)
        proxy[name] = {
            "estimator": "sklearn.mutual_info_classif (KSG k-NN, k=3), units=nats",
            "top_proxies": [{"feature": mi_feats[i], "mi_nats": round(float(mi[i]), 4)}
                            for i in top],
            "null_mean": round(float(null.mean()), 4),
            "null_p95": round(float(np.percentile(null, 95)), 4),
            "top_z": round(float((mi[top1] - null.mean()) / (null.std() + 1e-9)), 2),
        }
    out["proxy_audit"] = proxy

    print("[7/7] Clustering (DBSCAN, KMeans, PCA+KMeans, GMM) + seed sweep …")
    Xnum = pd.get_dummies(X, columns=cat_cols).select_dtypes(include=[np.number]).fillna(0)
    Xs = StandardScaler().fit_transform(Xnum.values)
    pca = PCA(n_components=10, random_state=RNG)
    Xp = pca.fit_transform(Xs)
    clus = {"pca_var_explained_10": round(float(pca.explained_variance_ratio_.sum()), 4),
            "families": {}}
    for k in [2, 3, 4]:
        lab = KMeans(n_clusters=k, random_state=RNG, n_init=10).fit_predict(Xs)
        clus["families"][f"kmeans_k{k}"] = round(float(silhouette_score(Xs, lab)), 4)
        labp = KMeans(n_clusters=k, random_state=RNG, n_init=10).fit_predict(Xp)
        clus["families"][f"pca_kmeans_k{k}"] = round(float(silhouette_score(Xp, labp)), 4)
        labg = GaussianMixture(n_components=k, random_state=RNG).fit_predict(Xs)
        clus["families"][f"gmm_k{k}"] = round(float(silhouette_score(Xs, labg)), 4)
    for eps in [1.5, 2.0, 2.5, 3.0]:
        lab = DBSCAN(eps=eps, min_samples=10).fit_predict(Xs)
        mask = lab != -1
        if len(np.unique(lab[mask])) >= 2:
            clus["families"][f"dbscan_eps{eps}"] = round(
                float(silhouette_score(Xs[mask], lab[mask])), 4)
        else:
            clus["families"][f"dbscan_eps{eps}"] = None
    clus["max_silhouette"] = max(v for v in clus["families"].values() if v is not None)
    clus["threshold_0.30_met"] = clus["max_silhouette"] >= 0.30
    out["clustering"] = clus

    # seed sensitivity: 7 seeds, 80/20 holdout, AUC per model
    seeds = [42, 123, 256, 512, 1000, 2024, 9999]
    seed_res = {"catboost": [], "logreg": [], "randomforest": []}
    for sd in seeds:
        Xtr2, Xte2, ytr2, yte2 = train_test_split(
            X, y, test_size=0.2, stratify=y, random_state=sd)
        mc = CatBoostClassifier(**{**CATBOOST_PARAMS, "random_seed": sd,
                                   "class_weights": {0: 1, 1: 5}})
        mc.fit(Pool(Xtr2[all_feats], ytr2, cat_features=cats_full))
        seed_res["catboost"].append(round(roc_auc_score(
            yte2, mc.predict_proba(Xte2[all_feats])[:, 1]), 4))
        for kind, key in [("logreg", "logreg"), ("rf", "randomforest")]:
            pipe = make_sklearn_pipe(kind, cats_full, [c for c in num_cols if c in all_feats])
            pipe.fit(Xtr2, ytr2)
            seed_res[key].append(round(roc_auc_score(
                yte2, pipe.predict_proba(Xte2)[:, 1]), 4))
    out["seed_sensitivity"] = {"seeds": seeds, **seed_res,
                               "catboost_mean": round(float(np.mean(seed_res["catboost"])), 4),
                               "catboost_range": [min(seed_res["catboost"]), max(seed_res["catboost"])]}

    # save
    (RESDIR / "empirical_run_summary.json").write_text(json.dumps(out, indent=2))
    np.savez(RESDIR / "arrays.npz",
             pooled_y=yt, pooled_prob=pr, pooled_pred=yp,
             holdout_y=yte, holdout_prob=p_hold,
             holdout_prob_logreg=holdout_probs["logreg"],
             holdout_prob_rf=holdout_probs["randomforest"],
             holdout_prob_dummy=holdout_probs["dummy"],
             shap_features=np.array([f for f, _ in shap_imp[:15]]),
             shap_values=np.array([v for _, v in shap_imp[:15]]),
             perm_features=np.array([f for f, _, _ in perm_imp[:15]]),
             perm_values=np.array([mn for _, mn, _ in perm_imp[:15]]),
             perm_std=np.array([sd for _, _, sd in perm_imp[:15]]))
    print(f"\nSaved -> {RESDIR/'empirical_run_summary.json'} and arrays.npz")
    print(f"CV AUC (CatBoost full, unweighted): "
          f"{out['models']['catboost_full_unweighted']['auc']}")
    print(f"Ablation: {out['ablation']}")
    print(f"Calibration primary(weighted) ECE: {out['calibration']['weighted_5x']['ece_uniform_10']} "
          f"CI {out['calibration']['weighted_5x']['ece_uniform_10_ci95']}; "
          f"unweighted ECE {out['calibration']['unweighted']['ece_uniform_10']}; "
          f"weighted mean_pred {out['calibration']['weighted_5x']['mean_pred']} vs base {y.mean():.3f}")
    print(f"Holdout confusion: {out['holdout']['confusion_matrix']} (n_pos={out['holdout']['n_positive']})")
    print(f"Fairness gender EOD {out['fairness']['gender']['eod']}, marital EOD {out['fairness']['marital']['eod']}, "
          f"age EOD {out['fairness']['ageband']['eod']}, compband V {out['fairness']['compband']['cramers_v']}")


if __name__ == "__main__":
    main()
